version: '3.8'

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - "5173:5173"
    volumes:
      - ./backend/data:/data
